export const SEATS = [
    {code:'1A', classType:'First class'},
    {code:'1B', classType:'First class'},
    {code:'1C', classType:'First class'},
    {code:'1D', classType:'First class'},
    {code:'1E', classType:'First class'},
    {code:'2A', classType:'First class'},
    {code:'2B', classType:'First class'},
    {code:'2C', classType:'First class'},
    {code:'2D', classType:'First class'},
    {code:'2E', classType:'First class'},
    {code:'3A', classType:'First class'},
    {code:'3B', classType:'First class'},
    {code:'3C', classType:'First class'},
    {code:'3D', classType:'First class'},
    {code:'3E', classType:'First class'},
    {code:'4A', classType:'Economic'},
    {code:'4B', classType:'Economic'},
    {code:'4C', classType:'Economic'},
    {code:'4D', classType:'Economic'},
    {code:'4E', classType:'Economic'},
    {code:'5A', classType:'Economic'},
    {code:'5B', classType:'Economic'},
    {code:'5C', classType:'Economic'},
    {code:'5D', classType:'Economic'},
    {code:'5E', classType:'Economic'},
    {code:'6A', classType:'Economic'},
    {code:'6B', classType:'Economic'},
    {code:'6C', classType:'Economic'},
    {code:'6D', classType:'Economic'},
    {code:'6E', classType:'Economic'},
    {code:'7A', classType:'Economic'},
    {code:'7B', classType:'Economic'},
    {code:'7C', classType:'Economic'},
    {code:'7D', classType:'Economic'},
    {code:'7E', classType:'Economic'},
    {code:'8A', classType:'Economic'},
    {code:'8B', classType:'Economic'},
    {code:'8C', classType:'Economic'},
    {code:'8D', classType:'Economic'},
    {code:'8E', classType:'Economic'},
    {code:'9A', classType:'Economic'},
    {code:'9B', classType:'Economic'},
    {code:'9C', classType:'Economic'},
    {code:'9D', classType:'Economic'},
    {code:'9E', classType:'Economic'}
]